version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  bull-monitor:
    image: ejhayes/nodejs-bull-monitor:latest
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      BULL_WATCH_QUEUE_PREFIXES: bull
      PORT: 3000
      UI: bull-master

volumes:
  postgres_data:
  redis_data:
